name: 'Terraform Validation and PR Creation'

on:
  repository_dispatch:
    types:
      - terraform-deploy
  push:
    branches:
      - development
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  validate-and-pr:
    name: 'Validate and Create PR'
    runs-on: ubuntu-latest
    environment: development
    defaults:
      run:
        working-directory: ./
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: main
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.5.0"
        
    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
      continue-on-error: true
      
    - name: Terraform Init
      id: init
      run: terraform init
      
    - name: Terraform Validate
      id: validate
      run: terraform validate

    - name: Create Pull Request
      id: cpr
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: "Merge development into main"
        pr_body: "Automated PR to merge recent changes from development into main"
        pr_label: "automated-pr"