name: 'Terraform Validation and PR Creation'

on:
  repository_dispatch:
    types:
      - terraform-deploy
  push:
    branches:
      - development
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  validate-and-pr:
    name: 'Validate and Create PR'
    runs-on: ubuntu-latest
    environment: development
    defaults:
      run:
        working-directory: ./
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.5.0"
        
    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
      continue-on-error: true
      
    - name: Terraform Init
      id: init
      run: terraform init
      
    - name: Terraform Validate
      id: validate
      run: terraform validate

    - name: Create Pull Request
      if: success() && github.ref == 'refs/heads/development'
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "feat: terraform infrastructure changes"
        title: "Infrastructure: Terraform Changes Ready for Review"
        body: |
          ## Terraform Changes Summary
          
          This PR contains infrastructure changes that have been validated:
          
          ### Validation Results
          ✨ Format check: ${{ steps.fmt.outcome }}
          🔄 Init: ${{ steps.init.outcome }}
          ✅ Validate: ${{ steps.validate.outcome }}
          
          ### Changes Include
          - Infrastructure modifications from development branch
          - Automated validation checks passed
          
          ### Next Steps
          1. Review the Terraform plan output
          2. Verify resource changes align with expectations
          3. Approve and merge to trigger deployment
          
          > Note: Please ensure all security and compliance requirements are met before merging.
        branch: development
        base: main
        labels: |
          terraform
          infrastructure
          automated
        reviewers: ${{ github.repository_owner }}
        draft: false
        delete-branch: false 