name: 'Terraform Validation and PR Creation'

on:
  repository_dispatch:
    types:
      - terraform-deploy
  push:
    branches:
      - development
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  validate-and-pr:
    name: 'Validate and Create PR'
    runs-on: ubuntu-latest
    environment: development
    defaults:
      run:
        working-directory: ./
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.5.0"
        
    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
      continue-on-error: true
      
    - name: Terraform Init
      id: init
      run: terraform init
      
    - name: Terraform Validate
      id: validate
      run: terraform validate

    - name: Create Pull Request
      if: success() && github.ref == 'refs/heads/development'
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore: terraform changes from development"
        title: "Terraform Changes Ready for Review"
        body: |
          This PR contains Terraform changes that have passed validation:
          - Format check: ${{ steps.fmt.outcome }}
          - Init: ${{ steps.init.outcome }}
          - Validate: ${{ steps.validate.outcome }}
          
          Please review the changes and merge to trigger HCP Terraform run.
        branch: development
        base: main
        labels: terraform
        draft: false 